
version: '3'

services:
  realtimequotesproducer:
    build:
      context: ./real_time_quotes_producer
    ports:
      - "8003:8003"
    networks:
      - backend   
    environment:
      DJANGO_SECRET_KEY: "django-insecure-)tw*btiaz$i1z@yy-xzp0a+ngda*tc$mxnj#%3bmdono+oe6eo"
      DJANGO_DEBUG: "True"
      DB_NAME: "defaultdb"
      DB_USER: "avnadmin"
      DB_PASSWORD: "AVNS_18I1eywxzSMn0TaBzxw"
      DB_HOST: "pg-6dd75e5-priyaarshinipallavi-3893.g.aivencloud.com" 
      DB_PORT: "22585"
      ALLOWED_HOSTS: "127.0.0.1,localhost,charts,realtimequotesproducer,riskservices"
      DB_SCHEMA: "stocks_schema"
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    networks:
      - backend   
  real_time_quotes_consumer:
    build:
      context: ./real_time_quotes_consumer
    ports:
      - "8002:8002"
    networks:
      - backend  
    environment:
      DJANGO_SECRET_KEY: "django-insecure-wsai*7b(o72o(=&0l9&skxdyxns7(3)c!exhozga^j-krh0u2u"
      DJANGO_DEBUG: "True"
      DB_NAME: "defaultdb"
      DB_USER: "avnadmin"
      DB_PASSWORD: "AVNS_18I1eywxzSMn0TaBzxw"
      DB_HOST: "pg-6dd75e5-priyaarshinipallavi-3893.g.aivencloud.com" 
      DB_PORT: "22585"
      DB_SCHEMA: "stocks_schema"  
      REDIS_HOST: "redis"
      ALLOWED_HOSTS: "localhost,charts,realtimequotesproducer,riskservices"
      KAFKA_BOOTSTRAP_SERVERS: "kafka-22753f33-priyaarshinipallavi-3893.g.aivencloud.com:22587" 
    depends_on:
      - redis
      - charts

  charts:
    build:
      context: ./stockcharts
    ports:
      - "8005:8005"
    networks:
      - backend  
    environment:
      - ALLOWED_HOSTS=localhost,charts 

  riskservices:
    build:
      context: ./risk_service
    ports:
      - "8009:8009"
    networks:
      - backend 
    depends_on:
      - redis   
    environment:
      DJANGO_SETTINGS_MODULE: "risk_service.settings"
      DJANGO_SECRET_KEY: "django-insecure-(3bskg&j@=%0u1t!(7g4=f#q&ulj*z2&^hr3($l)2@d*i&w^ae"
      DJANGO_DEBUG: "True"
      DB_NAME: "defaultdb"
      DB_USER: "avnadmin"
      DB_PASSWORD: "AVNS_18I1eywxzSMn0TaBzxw"
      DB_HOST: "pg-6dd75e5-priyaarshinipallavi-3893.g.aivencloud.com" 
      DB_PORT: "22585"
      ALLOWED_HOSTS: "127.0.0.1,localhost,charts,realtimequotesproducer,riskservices"
      DB_SCHEMA: "stocks_schema"  
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"

  celery_worker:
    build: ./risk_service
    depends_on:
      - redis
    networks:
      - backend   
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A risk_service worker --loglevel=info    
volumes:
  postgres_data:
networks:
  backend:
    driver: bridge  
