
version: '3'

services:
  real_time_quotes_producer:
    build:
      context: ./real_time_quotes_producer
    ports:
      - "8003:8003"
    environment:
      DJANGO_SECRET_KEY: "django-insecure-)tw*btiaz$i1z@yy-xzp0a+ngda*tc$mxnj#%3bmdono+oe6eo"
      DJANGO_DEBUG: "True"
      DB_NAME: "defaultdb"
      DB_USER: "avnadmin"
      DB_PASSWORD: "AVNS_18I1eywxzSMn0TaBzxw"
      DB_HOST: "pg-6dd75e5-priyaarshinipallavi-3893.g.aivencloud.com" 
      DB_PORT: "22585"
      DB_SCHEMA: "stocks_schema"
  redis:
    image: redis:5
    ports:
      - "6379:6379"
  real_time_quotes_consumer:
    build:
      context: ./real_time_quotes_consumer
    ports:
      - "8002:8002"
    environment:
      DJANGO_SECRET_KEY: "django-insecure-wsai*7b(o72o(=&0l9&skxdyxns7(3)c!exhozga^j-krh0u2u"
      DJANGO_DEBUG: "True"
      DB_NAME: "defaultdb"
      DB_USER: "avnadmin"
      DB_PASSWORD: "AVNS_18I1eywxzSMn0TaBzxw"
      DB_HOST: "pg-6dd75e5-priyaarshinipallavi-3893.g.aivencloud.com" 
      DB_PORT: "22585"
      DB_SCHEMA: "stocks_schema"  
      REDIS_HOST: "redis"
      KAFKA_BOOTSTRAP_SERVERS: "kafka-22753f33-priyaarshinipallavi-3893.g.aivencloud.com:22587" 
    depends_on:
      - redis



volumes:
  postgres_data: