# Generated by Django 3.2.25 on 2024-08-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='assets',
            field=models.ManyToManyField(related_name='portfolios', to='backtest.Asset'),
        ),
    ]
