# Generated by Django 3.2.25 on 2024-08-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_portfolio_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('result_data', models.JSONField()),
                ('benchmark_data', models.JSONField(blank=True, null=True)),
                ('comparison_metrics', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
