# Generated by Django 3.2.25 on 2024-08-15 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_curve', models.JSONField(help_text='Equity curve data as a list of portfolio values over time')),
                ('sharpe_ratio', models.FloatField(help_text='Sharpe ratio of the strategy during the backtest')),
                ('max_drawdown', models.FloatField(help_text='Maximum drawdown during the backtest')),
                ('total_return', models.FloatField(help_text='Total return percentage of the strategy')),
                ('start_date', models.DateField(help_text='Start date of the backtest')),
                ('end_date', models.DateField(help_text='End date of the backtest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Backtest Result',
                'verbose_name_plural': 'Backtest Results',
            },
        ),
        migrations.CreateModel(
            name='StrategyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_ma_period', models.IntegerField(default=50)),
                ('long_ma_period', models.IntegerField(default=200)),
                ('stop_loss', models.FloatField(default=0.05, help_text='Stop-loss percentage')),
                ('take_profit', models.FloatField(default=0.1, help_text='Take-profit percentage')),
                ('max_drawdown', models.FloatField(default=0.2, help_text='Maximum drawdown percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Strategy Configuration',
                'verbose_name_plural': 'Strategy Configurations',
            },
        ),
        migrations.CreateModel(
            name='TradingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Ticker symbol of the traded asset', max_length=10)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], help_text='Buy or Sell action', max_length=4)),
                ('price', models.FloatField(help_text='Price at which the trade was executed')),
                ('quantity', models.IntegerField(help_text='Quantity of the asset traded')),
                ('trade_time', models.DateTimeField(help_text='Time when the trade was executed')),
                ('profit_loss', models.FloatField(blank=True, help_text='Profit or loss from the trade', null=True)),
                ('stop_loss_triggered', models.BooleanField(default=False, help_text='Was the trade closed due to a stop-loss?')),
                ('take_profit_triggered', models.BooleanField(default=False, help_text='Was the trade closed due to take-profit?')),
                ('backtest_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='strategy.backtestresult')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='strategy.strategyconfig')),
            ],
            options={
                'verbose_name': 'Trading Log',
                'verbose_name_plural': 'Trading Logs',
            },
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='strategy.strategyconfig'),
        ),
    ]
